// LOCALHOST ### GET http://localhost:8080/contacts 
### GET http://localhost:8080/contacts/
### GET http://localhost:8080/contacts/:id




// LOCALHOST ### GET https://kofisapi.onrender.com/contacts 
### GET https://kofisapi.onrender.com/contacts/:id